# Generated by Django 3.2 on 2022-11-11 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('budget_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('budget_name', models.CharField(max_length=200)),
                ('budget_desc', models.CharField(max_length=200)),
                ('budget_income', models.IntegerField()),
                ('budget_balance', models.IntegerField()),
                ('payday', models.DateField()),
            ],
        ),
    ]
