# Generated by Django 2.2 on 2022-11-11 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_name', models.CharField(max_length=200)),
                ('bill_dueDate', models.DateField()),
                ('bill_amount', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(default='Generic', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_name', models.CharField(default='', max_length=200)),
                ('transaction_desc', models.CharField(default='', max_length=500)),
                ('transaction_date', models.DateField()),
                ('transaction_type', models.CharField(choices=[('Income', 'Income'), ('Debit', 'Debit')], default='Debit', max_length=15)),
                ('transaction_amount', models.PositiveIntegerField()),
                ('transaction_category', models.ManyToManyField(to='budget.Category')),
            ],
        ),
    ]
