# Generated by Django 2.2 on 2022-11-18 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_auto_20221118_1943'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
