# Generated by Django 2.2 on 2022-11-18 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_auto_20221118_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_category',
            field=models.CharField(choices=[('General', 'General'), ('Auto & Transport', 'Auto & Transport'), ('Bills & Utilities', 'Bills & Utilities'), ('Business', 'Business'), ('Education', 'Education'), ('Entertainment', 'Entertainment'), ('Fees & Charges', 'Fees & Charges'), ('Financial', 'Financial'), ('Food & Dining', 'Food & Dining'), ('Gifts & Donations', 'Gifts & Donations'), ('Groceries', 'Groceries'), ('Health & Fitness', 'Health & Fitness'), ('Income', 'Income'), ('Investments', 'Investments'), ('Kids', 'Kids'), ('Pets', 'Pets'), ('Shopping', 'Shopping'), ('Taxes', 'Taxes'), ('Transfer', 'Transfer'), ('Travel', 'Travel'), ('Other', 'Other')], default='Generic', max_length=200),
        ),
    ]
