# Generated by Django 2.2 on 2022-12-13 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0014_auto_20221213_0111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='bill_amount',
        ),
    ]
