# Generated by Django 2.2 on 2022-12-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0015_remove_bill_bill_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='bill_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
    ]
