# Generated by Django 2.2 on 2022-12-13 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0017_auto_20221213_1541'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Budget',
        ),
    ]
