# Generated by Django 2.2 on 2022-11-23 23:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20221123_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='payday',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
