# Generated by Django 2.2 on 2022-12-13 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20221128_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='available_balance_currency',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='before_balance_currency',
        ),
        migrations.AlterField(
            model_name='profile',
            name='available_balance',
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
        migrations.AlterField(
            model_name='profile',
            name='before_balance',
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
    ]
