# Generated by Django 2.2 on 2022-12-13 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20221213_0116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='available_balance',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='before_balance',
        ),
    ]
